# fly.toml app configuration file generated for pixel-place on 2024-06-22T01:57:06-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixel-place'
primary_region = 'ord'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/mnt/name/name.db'
  PHX_HOST = 'pixel.leastr.io'
  PORT = '8080'

[[mounts]]
  source = 'name'
  destination = '/mnt/name'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
